language: python
python:
  - "2.7"
before_install:

install:
  - pip install tox
script: tox
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_succes: change
    on_failure: always
